### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by keestux** [TD22057/T-Home#3]
First of all I want to thank you for sharing this code.

But may I also recommend to use a tools such as Pycharm? It helps to find problems before running the code. For example, Reply.py line 94 has self.bytes. But there is no .bytes in that class. Pycharm highlights this as a problem.

**Comment by TD22057** [comment]
Thanks for the suggestion... but I believe in this case that tool is incorrect.  That attribute is dynamically added by the struct unpack call.
