### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by bartje** [TD22057/T-Home#5]
I'm trying to use the T-home/.../sma scripts, but I'm receiving a number of error messages.  
The most common messages are import-errors 'ImportError: No module named tHome.sma'.  
Could you give me a couple of hints to resolve them?

Thanks

**Comment by TD22057** [comment]
You'll have to install python/tHome somewhere in your PYTHONPATH  like /usr/local/lib/python2.7/site-packages.  Or edit PYTHONPATH to point to it (assuming bash):

```
cd tHome
export PYTHONPATH=`pwd`/python
python2 bin/tHome-sma.py
```

You may have to edit the first line of the scripts depending on your system.  I wrote it awhile ago when python2 was standard (most systems are python3 now).  I also never bothered to make a setuptools script (though that shouldn't be that hard).  Also just an FYI but I sold the house w/ the panels and SMA inverter so I can help you get it running but I can't do much more than that at this point.

**Comment by bartje** [comment]
thanks, I just figured that out to. I started to adapt it for Python3, but I think that for now I will continue on your Python2 version.
