### ISSUE TITLE
Suggested start to python3 conversion

### ISSUE THREAD

**Issue by evanrich** [TD22057/T-Home#8]
Ted,

Thanks again for putting together this awesome project.   I started porting your code to be python3 compliant.  I stripped out everything except eagle for my Docker container, so I don't want to submit a PR for just that, but figured if you were interested in python3 porting, you could use this as a start:

https://github.com/evanrich/py-eagle-mqtt/commit/c584f7bf6ef3c018f6bf4ed76c194332587dfb41

FWIW, I used http://www.pythonconverter.com/ and it works pretty well for converting Python 2 to 3, just copy and paste in (I'm not a python dev so I had to use it).  Your eagle code runs with the changes I made in the commit above, hope it helps you.   If you'd like I can port the entire project maybe this weekend.

Thanks!

**Comment by evanrich** [comment]
I've flipped a few more eagle files, if you want I can convert your entire code base when I have the time.   I've also added in Price info from the meter.

**Comment by TD22057** [comment]
Feel free to do whatever you want.  I don't use this code base anymore (I don't have a lot of the hardware) so I'm just happy someone found it useful.

**Comment by evanrich** [comment]
https://github.com/evanrich/py-eagle-mqtt . converted to python 3.x in the repo listed, closing this.  Thanks!
